// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	browse "github.com/adambrett/go-fyne/pkg/browse"
	mock "github.com/stretchr/testify/mock"
)

// BrowsePicker is an autogenerated mock type for the Picker type
type BrowsePicker struct {
	mock.Mock
}

type BrowsePicker_Expecter struct {
	mock *mock.Mock
}

func (_m *BrowsePicker) EXPECT() *BrowsePicker_Expecter {
	return &BrowsePicker_Expecter{mock: &_m.Mock}
}

// Open provides a mock function with given fields: options, onSelected
func (_m *BrowsePicker) Open(options browse.OpenOptions, onSelected func(string)) {
	_m.Called(options, onSelected)
}

// BrowsePicker_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type BrowsePicker_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - options browse.OpenOptions
//   - onSelected func(string)
func (_e *BrowsePicker_Expecter) Open(options interface{}, onSelected interface{}) *BrowsePicker_Open_Call {
	return &BrowsePicker_Open_Call{Call: _e.mock.On("Open", options, onSelected)}
}

func (_c *BrowsePicker_Open_Call) Run(run func(options browse.OpenOptions, onSelected func(string))) *BrowsePicker_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(browse.OpenOptions), args[1].(func(string)))
	})
	return _c
}

func (_c *BrowsePicker_Open_Call) Return() *BrowsePicker_Open_Call {
	_c.Call.Return()
	return _c
}

func (_c *BrowsePicker_Open_Call) RunAndReturn(run func(browse.OpenOptions, func(string))) *BrowsePicker_Open_Call {
	_c.Run(run)
	return _c
}

// Save provides a mock function with given fields: options, onSelected
func (_m *BrowsePicker) Save(options browse.SaveOptions, onSelected func(string)) {
	_m.Called(options, onSelected)
}

// BrowsePicker_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type BrowsePicker_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - options browse.SaveOptions
//   - onSelected func(string)
func (_e *BrowsePicker_Expecter) Save(options interface{}, onSelected interface{}) *BrowsePicker_Save_Call {
	return &BrowsePicker_Save_Call{Call: _e.mock.On("Save", options, onSelected)}
}

func (_c *BrowsePicker_Save_Call) Run(run func(options browse.SaveOptions, onSelected func(string))) *BrowsePicker_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(browse.SaveOptions), args[1].(func(string)))
	})
	return _c
}

func (_c *BrowsePicker_Save_Call) Return() *BrowsePicker_Save_Call {
	_c.Call.Return()
	return _c
}

func (_c *BrowsePicker_Save_Call) RunAndReturn(run func(browse.SaveOptions, func(string))) *BrowsePicker_Save_Call {
	_c.Run(run)
	return _c
}

// NewBrowsePicker creates a new instance of BrowsePicker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrowsePicker(t interface {
	mock.TestingT
	Cleanup(func())
},
) *BrowsePicker {
	mock := &BrowsePicker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
