// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	iter "iter"

	mock "github.com/stretchr/testify/mock"

	project "github.com/adambrett/deckcheck/internal/project"
)

// ExportProject is an autogenerated mock type for the Project type
type ExportProject struct {
	mock.Mock
}

type ExportProject_Expecter struct {
	mock *mock.Mock
}

func (_m *ExportProject) EXPECT() *ExportProject_Expecter {
	return &ExportProject_Expecter{mock: &_m.Mock}
}

// ClassifiedRecords provides a mock function with given fields: _a0, _a1
func (_m *ExportProject) ClassifiedRecords(_a0 context.Context, _a1 []project.Question) iter.Seq2[project.ClassifiedRecord, error] {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClassifiedRecords")
	}

	var r0 iter.Seq2[project.ClassifiedRecord, error]
	if rf, ok := ret.Get(0).(func(context.Context, []project.Question) iter.Seq2[project.ClassifiedRecord, error]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[project.ClassifiedRecord, error])
		}
	}

	return r0
}

// ExportProject_ClassifiedRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClassifiedRecords'
type ExportProject_ClassifiedRecords_Call struct {
	*mock.Call
}

// ClassifiedRecords is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []project.Question
func (_e *ExportProject_Expecter) ClassifiedRecords(_a0 interface{}, _a1 interface{}) *ExportProject_ClassifiedRecords_Call {
	return &ExportProject_ClassifiedRecords_Call{Call: _e.mock.On("ClassifiedRecords", _a0, _a1)}
}

func (_c *ExportProject_ClassifiedRecords_Call) Run(run func(_a0 context.Context, _a1 []project.Question)) *ExportProject_ClassifiedRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]project.Question))
	})
	return _c
}

func (_c *ExportProject_ClassifiedRecords_Call) Return(_a0 iter.Seq2[project.ClassifiedRecord, error]) *ExportProject_ClassifiedRecords_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExportProject_ClassifiedRecords_Call) RunAndReturn(run func(context.Context, []project.Question) iter.Seq2[project.ClassifiedRecord, error]) *ExportProject_ClassifiedRecords_Call {
	_c.Call.Return(run)
	return _c
}

// DataColumns provides a mock function with no fields
func (_m *ExportProject) DataColumns() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DataColumns")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// ExportProject_DataColumns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DataColumns'
type ExportProject_DataColumns_Call struct {
	*mock.Call
}

// DataColumns is a helper method to define mock.On call
func (_e *ExportProject_Expecter) DataColumns() *ExportProject_DataColumns_Call {
	return &ExportProject_DataColumns_Call{Call: _e.mock.On("DataColumns")}
}

func (_c *ExportProject_DataColumns_Call) Run(run func()) *ExportProject_DataColumns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExportProject_DataColumns_Call) Return(_a0 []string) *ExportProject_DataColumns_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExportProject_DataColumns_Call) RunAndReturn(run func() []string) *ExportProject_DataColumns_Call {
	_c.Call.Return(run)
	return _c
}

// Questions provides a mock function with given fields: _a0
func (_m *ExportProject) Questions(_a0 context.Context) ([]project.Question, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Questions")
	}

	var r0 []project.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]project.Question, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []project.Question); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]project.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExportProject_Questions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Questions'
type ExportProject_Questions_Call struct {
	*mock.Call
}

// Questions is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *ExportProject_Expecter) Questions(_a0 interface{}) *ExportProject_Questions_Call {
	return &ExportProject_Questions_Call{Call: _e.mock.On("Questions", _a0)}
}

func (_c *ExportProject_Questions_Call) Run(run func(_a0 context.Context)) *ExportProject_Questions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ExportProject_Questions_Call) Return(_a0 []project.Question, _a1 error) *ExportProject_Questions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExportProject_Questions_Call) RunAndReturn(run func(context.Context) ([]project.Question, error)) *ExportProject_Questions_Call {
	_c.Call.Return(run)
	return _c
}

// NewExportProject creates a new instance of ExportProject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExportProject(t interface {
	mock.TestingT
	Cleanup(func())
},
) *ExportProject {
	mock := &ExportProject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
