// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	iter "iter"

	mock "github.com/stretchr/testify/mock"

	project "github.com/adambrett/deckcheck/internal/project"
)

// AppProject is an autogenerated mock type for the Project type
type AppProject struct {
	mock.Mock
}

type AppProject_Expecter struct {
	mock *mock.Mock
}

func (_m *AppProject) EXPECT() *AppProject_Expecter {
	return &AppProject_Expecter{mock: &_m.Mock}
}

// ClassifiedRecords provides a mock function with given fields: _a0, _a1
func (_m *AppProject) ClassifiedRecords(_a0 context.Context, _a1 []project.Question) iter.Seq2[project.ClassifiedRecord, error] {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClassifiedRecords")
	}

	var r0 iter.Seq2[project.ClassifiedRecord, error]
	if rf, ok := ret.Get(0).(func(context.Context, []project.Question) iter.Seq2[project.ClassifiedRecord, error]); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[project.ClassifiedRecord, error])
		}
	}

	return r0
}

// AppProject_ClassifiedRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClassifiedRecords'
type AppProject_ClassifiedRecords_Call struct {
	*mock.Call
}

// ClassifiedRecords is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []project.Question
func (_e *AppProject_Expecter) ClassifiedRecords(_a0 interface{}, _a1 interface{}) *AppProject_ClassifiedRecords_Call {
	return &AppProject_ClassifiedRecords_Call{Call: _e.mock.On("ClassifiedRecords", _a0, _a1)}
}

func (_c *AppProject_ClassifiedRecords_Call) Run(run func(_a0 context.Context, _a1 []project.Question)) *AppProject_ClassifiedRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]project.Question))
	})
	return _c
}

func (_c *AppProject_ClassifiedRecords_Call) Return(_a0 iter.Seq2[project.ClassifiedRecord, error]) *AppProject_ClassifiedRecords_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppProject_ClassifiedRecords_Call) RunAndReturn(run func(context.Context, []project.Question) iter.Seq2[project.ClassifiedRecord, error]) *AppProject_ClassifiedRecords_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *AppProject) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AppProject_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type AppProject_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *AppProject_Expecter) Close() *AppProject_Close_Call {
	return &AppProject_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *AppProject_Close_Call) Run(run func()) *AppProject_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppProject_Close_Call) Return(_a0 error) *AppProject_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppProject_Close_Call) RunAndReturn(run func() error) *AppProject_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DataColumns provides a mock function with no fields
func (_m *AppProject) DataColumns() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DataColumns")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// AppProject_DataColumns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DataColumns'
type AppProject_DataColumns_Call struct {
	*mock.Call
}

// DataColumns is a helper method to define mock.On call
func (_e *AppProject_Expecter) DataColumns() *AppProject_DataColumns_Call {
	return &AppProject_DataColumns_Call{Call: _e.mock.On("DataColumns")}
}

func (_c *AppProject_DataColumns_Call) Run(run func()) *AppProject_DataColumns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AppProject_DataColumns_Call) Return(_a0 []string) *AppProject_DataColumns_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppProject_DataColumns_Call) RunAndReturn(run func() []string) *AppProject_DataColumns_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClassification provides a mock function with given fields: ctx, rowID, questionID
func (_m *AppProject) DeleteClassification(ctx context.Context, rowID int, questionID int) error {
	ret := _m.Called(ctx, rowID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClassification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, rowID, questionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AppProject_DeleteClassification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClassification'
type AppProject_DeleteClassification_Call struct {
	*mock.Call
}

// DeleteClassification is a helper method to define mock.On call
//   - ctx context.Context
//   - rowID int
//   - questionID int
func (_e *AppProject_Expecter) DeleteClassification(ctx interface{}, rowID interface{}, questionID interface{}) *AppProject_DeleteClassification_Call {
	return &AppProject_DeleteClassification_Call{Call: _e.mock.On("DeleteClassification", ctx, rowID, questionID)}
}

func (_c *AppProject_DeleteClassification_Call) Run(run func(ctx context.Context, rowID int, questionID int)) *AppProject_DeleteClassification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *AppProject_DeleteClassification_Call) Return(_a0 error) *AppProject_DeleteClassification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppProject_DeleteClassification_Call) RunAndReturn(run func(context.Context, int, int) error) *AppProject_DeleteClassification_Call {
	_c.Call.Return(run)
	return _c
}

// NextUnclassified provides a mock function with given fields: ctx, fromIndex
func (_m *AppProject) NextUnclassified(ctx context.Context, fromIndex int) (int, bool, error) {
	ret := _m.Called(ctx, fromIndex)

	if len(ret) == 0 {
		panic("no return value specified for NextUnclassified")
	}

	var r0 int
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, bool, error)); ok {
		return rf(ctx, fromIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, fromIndex)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = rf(ctx, fromIndex)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, fromIndex)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AppProject_NextUnclassified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextUnclassified'
type AppProject_NextUnclassified_Call struct {
	*mock.Call
}

// NextUnclassified is a helper method to define mock.On call
//   - ctx context.Context
//   - fromIndex int
func (_e *AppProject_Expecter) NextUnclassified(ctx interface{}, fromIndex interface{}) *AppProject_NextUnclassified_Call {
	return &AppProject_NextUnclassified_Call{Call: _e.mock.On("NextUnclassified", ctx, fromIndex)}
}

func (_c *AppProject_NextUnclassified_Call) Run(run func(ctx context.Context, fromIndex int)) *AppProject_NextUnclassified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *AppProject_NextUnclassified_Call) Return(_a0 int, _a1 bool, _a2 error) *AppProject_NextUnclassified_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AppProject_NextUnclassified_Call) RunAndReturn(run func(context.Context, int) (int, bool, error)) *AppProject_NextUnclassified_Call {
	_c.Call.Return(run)
	return _c
}

// PreviousUnclassified provides a mock function with given fields: ctx, beforeIndex
func (_m *AppProject) PreviousUnclassified(ctx context.Context, beforeIndex int) (int, bool, error) {
	ret := _m.Called(ctx, beforeIndex)

	if len(ret) == 0 {
		panic("no return value specified for PreviousUnclassified")
	}

	var r0 int
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, bool, error)); ok {
		return rf(ctx, beforeIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, beforeIndex)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = rf(ctx, beforeIndex)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, beforeIndex)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AppProject_PreviousUnclassified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreviousUnclassified'
type AppProject_PreviousUnclassified_Call struct {
	*mock.Call
}

// PreviousUnclassified is a helper method to define mock.On call
//   - ctx context.Context
//   - beforeIndex int
func (_e *AppProject_Expecter) PreviousUnclassified(ctx interface{}, beforeIndex interface{}) *AppProject_PreviousUnclassified_Call {
	return &AppProject_PreviousUnclassified_Call{Call: _e.mock.On("PreviousUnclassified", ctx, beforeIndex)}
}

func (_c *AppProject_PreviousUnclassified_Call) Run(run func(ctx context.Context, beforeIndex int)) *AppProject_PreviousUnclassified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *AppProject_PreviousUnclassified_Call) Return(_a0 int, _a1 bool, _a2 error) *AppProject_PreviousUnclassified_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AppProject_PreviousUnclassified_Call) RunAndReturn(run func(context.Context, int) (int, bool, error)) *AppProject_PreviousUnclassified_Call {
	_c.Call.Return(run)
	return _c
}

// Progress provides a mock function with given fields: _a0
func (_m *AppProject) Progress(_a0 context.Context) (int, int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Progress")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AppProject_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type AppProject_Progress_Call struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *AppProject_Expecter) Progress(_a0 interface{}) *AppProject_Progress_Call {
	return &AppProject_Progress_Call{Call: _e.mock.On("Progress", _a0)}
}

func (_c *AppProject_Progress_Call) Run(run func(_a0 context.Context)) *AppProject_Progress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AppProject_Progress_Call) Return(classified int, total int, err error) *AppProject_Progress_Call {
	_c.Call.Return(classified, total, err)
	return _c
}

func (_c *AppProject_Progress_Call) RunAndReturn(run func(context.Context) (int, int, error)) *AppProject_Progress_Call {
	_c.Call.Return(run)
	return _c
}

// Questions provides a mock function with given fields: _a0
func (_m *AppProject) Questions(_a0 context.Context) ([]project.Question, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Questions")
	}

	var r0 []project.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]project.Question, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []project.Question); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]project.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AppProject_Questions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Questions'
type AppProject_Questions_Call struct {
	*mock.Call
}

// Questions is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *AppProject_Expecter) Questions(_a0 interface{}) *AppProject_Questions_Call {
	return &AppProject_Questions_Call{Call: _e.mock.On("Questions", _a0)}
}

func (_c *AppProject_Questions_Call) Run(run func(_a0 context.Context)) *AppProject_Questions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AppProject_Questions_Call) Return(_a0 []project.Question, _a1 error) *AppProject_Questions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AppProject_Questions_Call) RunAndReturn(run func(context.Context) ([]project.Question, error)) *AppProject_Questions_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function with given fields: _a0, _a1
func (_m *AppProject) Record(_a0 context.Context, _a1 int) (*project.Record, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 *project.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*project.Record, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *project.Record); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*project.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AppProject_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type AppProject_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
func (_e *AppProject_Expecter) Record(_a0 interface{}, _a1 interface{}) *AppProject_Record_Call {
	return &AppProject_Record_Call{Call: _e.mock.On("Record", _a0, _a1)}
}

func (_c *AppProject_Record_Call) Run(run func(_a0 context.Context, _a1 int)) *AppProject_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *AppProject_Record_Call) Return(_a0 *project.Record, _a1 error) *AppProject_Record_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AppProject_Record_Call) RunAndReturn(run func(context.Context, int) (*project.Record, error)) *AppProject_Record_Call {
	_c.Call.Return(run)
	return _c
}

// RecordCount provides a mock function with given fields: _a0
func (_m *AppProject) RecordCount(_a0 context.Context) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RecordCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AppProject_RecordCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordCount'
type AppProject_RecordCount_Call struct {
	*mock.Call
}

// RecordCount is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *AppProject_Expecter) RecordCount(_a0 interface{}) *AppProject_RecordCount_Call {
	return &AppProject_RecordCount_Call{Call: _e.mock.On("RecordCount", _a0)}
}

func (_c *AppProject_RecordCount_Call) Run(run func(_a0 context.Context)) *AppProject_RecordCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AppProject_RecordCount_Call) Return(_a0 int, _a1 error) *AppProject_RecordCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AppProject_RecordCount_Call) RunAndReturn(run func(context.Context) (int, error)) *AppProject_RecordCount_Call {
	_c.Call.Return(run)
	return _c
}

// SaveClassification provides a mock function with given fields: ctx, rowID, questionID, answerID
func (_m *AppProject) SaveClassification(ctx context.Context, rowID int, questionID int, answerID int) error {
	ret := _m.Called(ctx, rowID, questionID, answerID)

	if len(ret) == 0 {
		panic("no return value specified for SaveClassification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) error); ok {
		r0 = rf(ctx, rowID, questionID, answerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AppProject_SaveClassification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveClassification'
type AppProject_SaveClassification_Call struct {
	*mock.Call
}

// SaveClassification is a helper method to define mock.On call
//   - ctx context.Context
//   - rowID int
//   - questionID int
//   - answerID int
func (_e *AppProject_Expecter) SaveClassification(ctx interface{}, rowID interface{}, questionID interface{}, answerID interface{}) *AppProject_SaveClassification_Call {
	return &AppProject_SaveClassification_Call{Call: _e.mock.On("SaveClassification", ctx, rowID, questionID, answerID)}
}

func (_c *AppProject_SaveClassification_Call) Run(run func(ctx context.Context, rowID int, questionID int, answerID int)) *AppProject_SaveClassification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *AppProject_SaveClassification_Call) Return(_a0 error) *AppProject_SaveClassification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppProject_SaveClassification_Call) RunAndReturn(run func(context.Context, int, int, int) error) *AppProject_SaveClassification_Call {
	_c.Call.Return(run)
	return _c
}

// NewAppProject creates a new instance of AppProject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppProject(t interface {
	mock.TestingT
	Cleanup(func())
},
) *AppProject {
	mock := &AppProject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
