// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ClassifierExporter is an autogenerated mock type for the Exporter type
type ClassifierExporter struct {
	mock.Mock
}

type ClassifierExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *ClassifierExporter) EXPECT() *ClassifierExporter_Expecter {
	return &ClassifierExporter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: _a0, _a1
func (_m *ClassifierExporter) Write(_a0 context.Context, _a1 string) (int, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClassifierExporter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type ClassifierExporter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *ClassifierExporter_Expecter) Write(_a0 interface{}, _a1 interface{}) *ClassifierExporter_Write_Call {
	return &ClassifierExporter_Write_Call{Call: _e.mock.On("Write", _a0, _a1)}
}

func (_c *ClassifierExporter_Write_Call) Run(run func(_a0 context.Context, _a1 string)) *ClassifierExporter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClassifierExporter_Write_Call) Return(_a0 int, _a1 error) *ClassifierExporter_Write_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClassifierExporter_Write_Call) RunAndReturn(run func(context.Context, string) (int, error)) *ClassifierExporter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewClassifierExporter creates a new instance of ClassifierExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassifierExporter(t interface {
	mock.TestingT
	Cleanup(func())
},
) *ClassifierExporter {
	mock := &ClassifierExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
