// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	project "github.com/adambrett/deckcheck/internal/project"
	mock "github.com/stretchr/testify/mock"
)

// ClassifierProject is an autogenerated mock type for the Project type
type ClassifierProject struct {
	mock.Mock
}

type ClassifierProject_Expecter struct {
	mock *mock.Mock
}

func (_m *ClassifierProject) EXPECT() *ClassifierProject_Expecter {
	return &ClassifierProject_Expecter{mock: &_m.Mock}
}

// DeleteClassification provides a mock function with given fields: ctx, rowID, questionID
func (_m *ClassifierProject) DeleteClassification(ctx context.Context, rowID int, questionID int) error {
	ret := _m.Called(ctx, rowID, questionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClassification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, rowID, questionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClassifierProject_DeleteClassification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClassification'
type ClassifierProject_DeleteClassification_Call struct {
	*mock.Call
}

// DeleteClassification is a helper method to define mock.On call
//   - ctx context.Context
//   - rowID int
//   - questionID int
func (_e *ClassifierProject_Expecter) DeleteClassification(ctx interface{}, rowID interface{}, questionID interface{}) *ClassifierProject_DeleteClassification_Call {
	return &ClassifierProject_DeleteClassification_Call{Call: _e.mock.On("DeleteClassification", ctx, rowID, questionID)}
}

func (_c *ClassifierProject_DeleteClassification_Call) Run(run func(ctx context.Context, rowID int, questionID int)) *ClassifierProject_DeleteClassification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *ClassifierProject_DeleteClassification_Call) Return(_a0 error) *ClassifierProject_DeleteClassification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClassifierProject_DeleteClassification_Call) RunAndReturn(run func(context.Context, int, int) error) *ClassifierProject_DeleteClassification_Call {
	_c.Call.Return(run)
	return _c
}

// NextUnclassified provides a mock function with given fields: ctx, fromIndex
func (_m *ClassifierProject) NextUnclassified(ctx context.Context, fromIndex int) (int, bool, error) {
	ret := _m.Called(ctx, fromIndex)

	if len(ret) == 0 {
		panic("no return value specified for NextUnclassified")
	}

	var r0 int
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, bool, error)); ok {
		return rf(ctx, fromIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, fromIndex)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = rf(ctx, fromIndex)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, fromIndex)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClassifierProject_NextUnclassified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextUnclassified'
type ClassifierProject_NextUnclassified_Call struct {
	*mock.Call
}

// NextUnclassified is a helper method to define mock.On call
//   - ctx context.Context
//   - fromIndex int
func (_e *ClassifierProject_Expecter) NextUnclassified(ctx interface{}, fromIndex interface{}) *ClassifierProject_NextUnclassified_Call {
	return &ClassifierProject_NextUnclassified_Call{Call: _e.mock.On("NextUnclassified", ctx, fromIndex)}
}

func (_c *ClassifierProject_NextUnclassified_Call) Run(run func(ctx context.Context, fromIndex int)) *ClassifierProject_NextUnclassified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ClassifierProject_NextUnclassified_Call) Return(_a0 int, _a1 bool, _a2 error) *ClassifierProject_NextUnclassified_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ClassifierProject_NextUnclassified_Call) RunAndReturn(run func(context.Context, int) (int, bool, error)) *ClassifierProject_NextUnclassified_Call {
	_c.Call.Return(run)
	return _c
}

// PreviousUnclassified provides a mock function with given fields: ctx, beforeIndex
func (_m *ClassifierProject) PreviousUnclassified(ctx context.Context, beforeIndex int) (int, bool, error) {
	ret := _m.Called(ctx, beforeIndex)

	if len(ret) == 0 {
		panic("no return value specified for PreviousUnclassified")
	}

	var r0 int
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, bool, error)); ok {
		return rf(ctx, beforeIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, beforeIndex)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = rf(ctx, beforeIndex)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, beforeIndex)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClassifierProject_PreviousUnclassified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreviousUnclassified'
type ClassifierProject_PreviousUnclassified_Call struct {
	*mock.Call
}

// PreviousUnclassified is a helper method to define mock.On call
//   - ctx context.Context
//   - beforeIndex int
func (_e *ClassifierProject_Expecter) PreviousUnclassified(ctx interface{}, beforeIndex interface{}) *ClassifierProject_PreviousUnclassified_Call {
	return &ClassifierProject_PreviousUnclassified_Call{Call: _e.mock.On("PreviousUnclassified", ctx, beforeIndex)}
}

func (_c *ClassifierProject_PreviousUnclassified_Call) Run(run func(ctx context.Context, beforeIndex int)) *ClassifierProject_PreviousUnclassified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ClassifierProject_PreviousUnclassified_Call) Return(_a0 int, _a1 bool, _a2 error) *ClassifierProject_PreviousUnclassified_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ClassifierProject_PreviousUnclassified_Call) RunAndReturn(run func(context.Context, int) (int, bool, error)) *ClassifierProject_PreviousUnclassified_Call {
	_c.Call.Return(run)
	return _c
}

// Progress provides a mock function with given fields: _a0
func (_m *ClassifierProject) Progress(_a0 context.Context) (int, int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Progress")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClassifierProject_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type ClassifierProject_Progress_Call struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *ClassifierProject_Expecter) Progress(_a0 interface{}) *ClassifierProject_Progress_Call {
	return &ClassifierProject_Progress_Call{Call: _e.mock.On("Progress", _a0)}
}

func (_c *ClassifierProject_Progress_Call) Run(run func(_a0 context.Context)) *ClassifierProject_Progress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ClassifierProject_Progress_Call) Return(classified int, total int, err error) *ClassifierProject_Progress_Call {
	_c.Call.Return(classified, total, err)
	return _c
}

func (_c *ClassifierProject_Progress_Call) RunAndReturn(run func(context.Context) (int, int, error)) *ClassifierProject_Progress_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function with given fields: _a0, _a1
func (_m *ClassifierProject) Record(_a0 context.Context, _a1 int) (*project.Record, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 *project.Record
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*project.Record, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *project.Record); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*project.Record)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClassifierProject_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type ClassifierProject_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int
func (_e *ClassifierProject_Expecter) Record(_a0 interface{}, _a1 interface{}) *ClassifierProject_Record_Call {
	return &ClassifierProject_Record_Call{Call: _e.mock.On("Record", _a0, _a1)}
}

func (_c *ClassifierProject_Record_Call) Run(run func(_a0 context.Context, _a1 int)) *ClassifierProject_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ClassifierProject_Record_Call) Return(_a0 *project.Record, _a1 error) *ClassifierProject_Record_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClassifierProject_Record_Call) RunAndReturn(run func(context.Context, int) (*project.Record, error)) *ClassifierProject_Record_Call {
	_c.Call.Return(run)
	return _c
}

// RecordCount provides a mock function with given fields: _a0
func (_m *ClassifierProject) RecordCount(_a0 context.Context) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RecordCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClassifierProject_RecordCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordCount'
type ClassifierProject_RecordCount_Call struct {
	*mock.Call
}

// RecordCount is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *ClassifierProject_Expecter) RecordCount(_a0 interface{}) *ClassifierProject_RecordCount_Call {
	return &ClassifierProject_RecordCount_Call{Call: _e.mock.On("RecordCount", _a0)}
}

func (_c *ClassifierProject_RecordCount_Call) Run(run func(_a0 context.Context)) *ClassifierProject_RecordCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ClassifierProject_RecordCount_Call) Return(_a0 int, _a1 error) *ClassifierProject_RecordCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClassifierProject_RecordCount_Call) RunAndReturn(run func(context.Context) (int, error)) *ClassifierProject_RecordCount_Call {
	_c.Call.Return(run)
	return _c
}

// SaveClassification provides a mock function with given fields: ctx, rowID, questionID, answerID
func (_m *ClassifierProject) SaveClassification(ctx context.Context, rowID int, questionID int, answerID int) error {
	ret := _m.Called(ctx, rowID, questionID, answerID)

	if len(ret) == 0 {
		panic("no return value specified for SaveClassification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) error); ok {
		r0 = rf(ctx, rowID, questionID, answerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClassifierProject_SaveClassification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveClassification'
type ClassifierProject_SaveClassification_Call struct {
	*mock.Call
}

// SaveClassification is a helper method to define mock.On call
//   - ctx context.Context
//   - rowID int
//   - questionID int
//   - answerID int
func (_e *ClassifierProject_Expecter) SaveClassification(ctx interface{}, rowID interface{}, questionID interface{}, answerID interface{}) *ClassifierProject_SaveClassification_Call {
	return &ClassifierProject_SaveClassification_Call{Call: _e.mock.On("SaveClassification", ctx, rowID, questionID, answerID)}
}

func (_c *ClassifierProject_SaveClassification_Call) Run(run func(ctx context.Context, rowID int, questionID int, answerID int)) *ClassifierProject_SaveClassification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ClassifierProject_SaveClassification_Call) Return(_a0 error) *ClassifierProject_SaveClassification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClassifierProject_SaveClassification_Call) RunAndReturn(run func(context.Context, int, int, int) error) *ClassifierProject_SaveClassification_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGridAnnotation provides a mock function with given fields: ctx, rowID, questionID, value
func (_m *ClassifierProject) SaveGridAnnotation(ctx context.Context, rowID int, questionID int, value string) error {
	ret := _m.Called(ctx, rowID, questionID, value)

	if len(ret) == 0 {
		panic("no return value specified for SaveGridAnnotation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) error); ok {
		r0 = rf(ctx, rowID, questionID, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClassifierProject_SaveGridAnnotation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGridAnnotation'
type ClassifierProject_SaveGridAnnotation_Call struct {
	*mock.Call
}

// SaveGridAnnotation is a helper method to define mock.On call
//   - ctx context.Context
//   - rowID int
//   - questionID int
//   - value string
func (_e *ClassifierProject_Expecter) SaveGridAnnotation(ctx interface{}, rowID interface{}, questionID interface{}, value interface{}) *ClassifierProject_SaveGridAnnotation_Call {
	return &ClassifierProject_SaveGridAnnotation_Call{Call: _e.mock.On("SaveGridAnnotation", ctx, rowID, questionID, value)}
}

func (_c *ClassifierProject_SaveGridAnnotation_Call) Run(run func(ctx context.Context, rowID int, questionID int, value string)) *ClassifierProject_SaveGridAnnotation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *ClassifierProject_SaveGridAnnotation_Call) Return(_a0 error) *ClassifierProject_SaveGridAnnotation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClassifierProject_SaveGridAnnotation_Call) RunAndReturn(run func(context.Context, int, int, string) error) *ClassifierProject_SaveGridAnnotation_Call {
	_c.Call.Return(run)
	return _c
}

// NewClassifierProject creates a new instance of ClassifierProject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassifierProject(t interface {
	mock.TestingT
	Cleanup(func())
},
) *ClassifierProject {
	mock := &ClassifierProject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
